### ISSUE TITLE
Imagen inicial

### ISSUE THREAD

**Issue by applinet** [SAX2/consorciosenred#1]
La imagen inicial de la landing cambiarla por esta, que no sea tan oscura
![buenos-aires-wallpapers](https://github.com/user-attachments/assets/20c56f00-980c-462f-8be0-8b0e246e04eb)

**Comment by applinet** [comment]
Te paso los isologotipos 
![CeR logotipoblanco](https://github.com/user-attachments/assets/7f452573-3c16-436f-9ef1-1ea2aca1db96)
![CeR logotipoblanco](https://github.com/user-attachments/assets/ede2cb09-4110-47a0-a150-4078583d0f61)
[CeR logotipoazul.pdf](https://github.com/user-attachments/files/16313184/CeR.logotipoazul.pdf)
![CeR logotipoazul](https://github.com/user-attachments/assets/345c3328-7341-4d6e-b402-cf345a444caa)
![CeR isotipo
![CeR blanco](https://github.com/user-attachments/assets/4c8a3bbe-24f8-4fe5-ba60-20a745ecb211)
 circulo](https://github.com/user-attachments/assets/2264180f-3cbe-4dae-aec5-3f6f686ee731)

**Comment by SAX2** [comment]
Preview con logo original: [Uploading Desktop - 6 - logo original.pdf…]()
Preview con rediseño de logo:  [Desktop - 6.pdf](https://github.com/user-attachments/files/16313655/Desktop.-.6.pdf)

Añadi la imagen de fondo

**Comment by applinet** [comment]
Barbaro, segui con esto
Preview con rediseño de logo: [Desktop - 6.pdf](https://github.com/user-attachments/files/16313655/Desktop.-.6.pdf)
