### ISSUE TITLE
Posibilidad de guardarcredenciales. Ocultar/mostrar la clave al tipear

### ISSUE THREAD

**Issue by applinet** [SAX2/consorciosenred#2]
![Screenshot 2024-07-29 at 11 01 13](https://github.com/user-attachments/assets/84824253-4e0d-4d72-93c6-54cbe13b5d14)

- Agregar una opción para guardar los datos de usuario: usuario y password
- el password, al tipearlo, por defecto no debería mostrarlo. Agregar una opción para mostar / ocultar password

**Comment by SAX2** [comment]
Añadido en bdce5e8438b753b042409ab1fdd336f4ccb7d769
